# Site settings
title: UVA IRL Group
email: mr2an@virginia.edu
description: ""
baseurl: ""
url: "https://irl-grp.net"
twitter_username: 
github_username: mrucker 

# Build settings
markdown: kramdown
permalink: none
